### ISSUE TITLE
Why no duplicate DHCP options supported?

### ISSUE THREAD

**Issue by zerxen** [nuagenetworks/vspk-examples#16]
Need to give a system multiple static routes via DHCP option 121. First one works as expected, but second one gets this error:

bambou.exceptions.BambouHTTPError: [HTTP 409(Conflict)] [{u'property': u'', u'descriptions': [{u'description': u'A DHCP option cannot appear more than once per entity (subnet, zone, domain, l2domain).', u'title': u'Duplicate DHCP option'}]}]

Why is this limit here (asking as issue because it doesn't make sense) and any ideas how to bypass it?

**Comment by zerxen** [comment]
FYI: Code example:
        new_actual_values = ['30.0.0.0/24','15.163.248.1']
        new_option = vsdk.NUDHCPOption(actual_type=121,actual_values=new_actual_values)
        subnet.create_child(new_option)
        
        new_actual_values = ['15.163.248.0/24','15.163.248.1']
        new_option = vsdk.NUDHCPOption(actual_type=121,actual_values=new_actual_values)
        subnet.create_child(new_option)

**Comment by pdellaert** [comment]
I'm going to check internally... i thought there was a way, but after some testing, i'm not sure anymore :s

**Comment by pdellaert** [comment]
You can not do this through the actual_type and actual_values, you have to do this through the HEX type and value:
```python
dhcpoption = vsdk.NUDHCPOption(type=79, value='18C0A80A0A00000118C0A80B0A000001')
dom.create_child(dhcpoption)
```

The value corresponds with:
192.168.10.0/24 via 10.0.0.1
192.168.11.0/24 via 10.0.0.1

You can calculate this hex string with this gist: https://gist.github.com/casebeer/8308838 (below is an adapted extract)
```
def hex_encode(route):
	return b"".join([b"%02x" % octet for octet in route])

routes = [
	(24, 192,168,10, 10,0,0,1 ), 
	(24, 192,168,11, 10,0,0,1 ) 
]
hex_value = b"".join(hex_encode(route) for route in routes)
```

I've noticed that after creating this, the actual values field looks a bit strange, because it only shows the router (10.0.0.1) only once. While it should show it twice. If you change the hex string to `18C0A80A0A00000118C0A80B0A000002` (first subnet routed through 10.0.0.1, second through 10.0.0.2), it does show both in the actual_values. 
Also, even tho the actual_values does not show the router correctly for the second subnet, it is properly configured in the VSD and pushed to the VMs.

**Comment by zerxen** [comment]
Well if the routes are correctly pushed to the VMs, that is all I need, I will start ignoring the actual* attributes and work exclusively with hex then. Will test asap and provide feedback / close this issue. 

PS: Will raise that with my nokia contacts as a GUI bug to fix.

**Comment by zerxen** [comment]
Ok, works like a charm via hex (including subsequent reading of the actual values after I worked around how to append more routes to the hex). Thanks, case closed. 

Z:\helion\SDN_devel\NextGen_FAST_alpha_v03>python2 project_fast.py nuage create dhcp-option-121 --dhcp-route-prefix "30.160.158.155" --dhcp-route-nexthop "29.203.248.1"  --entname HelloWorld2 --domname Instance1 --zonename private1 --subnetname subnet1  --dhcp-route-prefix-mask 32

Subnet found with name: subnet1
('32', '30', '160', '158', '155', '29', '203', '248', '1')
**value new(hex):201ea09e9b1dcbf801**

Z:\helion\SDN_devel\NextGen_FAST_alpha_v03>python2 project_fast.py nuage create dhcp-option-121 --dhcp-route-prefix "30.160.158.150" --dhcp-route-nexthop "29.203.248.1"  --entname HelloWorld2 --domname Instance1 --zonename private1 --subnetname subnet1  --dhcp-route-prefix-mask 32

Subnet found with name: subnet1
    DHCP OPTION
    type(hex): 79
value(hex):201ea09e9b1dcbf801
('32', '30', '160', '158', '150', '29', '203', '248', '1')
**value new(hex):201ea09e9b1dcbf801201ea09e961dcbf801**

Z:\helion\SDN_devel\NextGen_FAST_alpha_v03>python2 project_fast.py nuage show dhcp-options --entname HelloWorld2 --domname Instance1

DOMAIN: HelloWorld2
Zone: private1
  Subnet: subnet1
    DHCP OPTION
    type(hex): 79
        value:201ea09e9b1dcbf801201ea09e961dcbf801
        Route(from hex): 30.160.158.155/32 - 29.203.248.1
        Route(from hex): 30.160.158.150/32 - 29.203.248.1
        act. value:30.160.158.155/32
        act. value:29.203.248.1
        act. value:30.160.158.150/32
        act. value:29.203.248.1
