### ISSUE TITLE
Need help to create Vport

### ISSUE THREAD

**Issue by github0486795** [nuagenetworks/vspk-examples#52]
hi,

I haven't seen an example of how to create a Vport (type=BRIDGE) under either an L2Domain or Domain.

I have simple playbook to create a Vport but got stuck at the Vport creation.
The task create L2 domain works but it is stuck at the Vport creation.

 - name: Create L2 domain for VLAN 3900 with template "NXOS Fabric L2 Template"
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: L2Domain
      parent_id: "{{ eNSEenterprise.id }}"
      parent_type: Enterprise
      state: present
      properties:
        template_id: "{{ eNSEenterpriseL2Domaintemplates.id }}"
        name: "VLAN 3900"
        description: "Peter Ansible L2 Domain"
    register: eNSEl2domain

  - name: Create vport under L2 domain for VLAN 3900
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: VPorts
      parent_id: "{{ eNSEl2domain.id }}"
      parent_type: L2Domain
      state: present
      properties:
        name: "vport VLAN 3900"
        type: "BRIDGE"
        bridgeinterface: "Bridging"
        VLANID: "{{ eNSEGatewayPortVlan.id }}"
    register: eNSEl2domainvport

The error is shown below
"msg": "Unrecognised type specified"

**Comment by pdellaert** [comment]
@github0486795 , the type should be `VPort`, without the `s`.

**Comment by github0486795** [comment]
Hi,

Here is the related task

- name: Create vport under L2 domain for VLAN 3900
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: Vport
      parent_id: "{{ eNSEl2domain.id }}"
      parent_type: L2Domain
      state: present
      properties:
        name: "vport VLAN 3900"
        type: "BRIDGE"
        bridgeinterface: "Bridging"
        vlanid: "{{ eNSEGatewayPortVlan.id }}"
    register: eNSEl2domainvport


***********Below is the log of the Ansible ***********
msg": "Unrecognised type specified"


TASK [Create vport under L2 domain for VLAN 3900] ****************************************************************************************************************
task path: /home/nuage/eNSE/createL2Domain.yml:86
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: nuage
<localhost> EXEC /bin/sh -c 'echo ~nuage && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/nuage/.ansible/tmp `"&& mkdir /home/nuage/.ansible/tmp/ansible-tmp-1592236806.39-12078-166189458854062 && echo ansible-tmp-1592236806.39-12078-166189458854062="` echo /home/nuage/.ansible/tmp/ansible-tmp-1592236806.39-12078-166189458854062 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nuage/nuage_vspk.py
<localhost> PUT /home/nuage/.ansible/tmp/ansible-local-11914FBYc1t/tmpoiyJml TO /home/nuage/.ansible/tmp/ansible-tmp-1592236806.39-12078-166189458854062/AnsiballZ_nuage_vspk.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/nuage/.ansible/tmp/ansible-tmp-1592236806.39-12078-166189458854062/ /home/nuage/.ansible/tmp/ansible-tmp-1592236806.39-12078-166189458854062/AnsiballZ_nuage_vspk.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/nuage/.ansible/tmp/ansible-tmp-1592236806.39-12078-166189458854062/AnsiballZ_nuage_vspk.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/nuage/.ansible/tmp/ansible-tmp-1592236806.39-12078-166189458854062/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_nuage_vspk_payload_IkyZTn/ansible_nuage_vspk_payload.zip/ansible/modules/network/nuage/nuage_vspk.py", line 462, in _verify_input
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth": {
                "api_certificate": null,
                "api_enterprise": "csp",
                "api_key": null,
                "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "api_url": "https://10.75.65.79:8443",
                "api_username": "csproot",
                "api_version": "v5_0"
            },
            "children": null,
            "command": null,
            "id": null,
            "match_filter": null,
            "parent_id": "09e55717-47aa-4f40-b6d1-9bf363aa4473",
            "parent_type": "L2Domain",
            "properties": {
                "bridgeinterface": "Bridging",
                "name": "vport VLAN 3900",
                "type": "BRIDGE",
                "vlanid": "621078a5-a465-4269-9273-fc9656479d50"
            },
            "state": "present",
            "type": "Vport"
        }
    },
    "msg": "Unrecognised type specified"
}
PLAY RECAP *******************************************************************************************************************************************************
localhost                  : ok=6    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by pdellaert** [comment]
You seem to have missed the capital P in `Vport`, where it should be `VPort`

**Comment by github0486795** [comment]
Awesome!  It works.  I tried multiple things with all CAPs and lower CAPs but missing key combination of the “VPorts”.

Do I have to use a separate task for the bridgeinterfaces, or can the bridgeinterfaces be part of the VPort creation task?

I used properties bridgeinterfaces under VPort but bridgeinterface doesn’t get created


- name: Create vport under L2 domain for VLAN 3900
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: VPort
      parent_id: "{{ eNSEl2domain.id }}"
      parent_type: L2Domain
      state: present
      properties:
        name: "vport VLAN 3900"
        description: "Testing Bridge"
        type: "BRIDGE"
        bridgeinterfaces: name="Bridging"
        address_spoofing: "ENABLED"
        vlanid: "{{ eNSEGatewayPortVlan.id }}"
    register: eNSEl2domainvport

**Comment by pdellaert** [comment]
Yes, that should be a separate task, somthing like:
```
- name: Create bridge interface for VPort
    delegate_to: localhost
    nuage_vspk:
      auth: "{{ nuage_auth }}"
      type: BridgeInterface
      parent_id: "{{ eNSEl2domainvport.id }}"
      parent_type: VPort
      state: present
      properties:
        name: "Bridge Interface VLAN 3900"
    register: eNSEl2domainbridgeinterface
```

**Comment by github0486795** [comment]
Thanks much for your help!

**Comment by pdellaert** [comment]
Very welcome :)
